### ISSUE TITLE
Iterating through the last 100 or so blocks works only for about 30% of the BitcoinExtendedClient.getBlock(int blockNumber)

### ISSUE THREAD

**Issue by milansismanovic** [ConsensusJ/consensusj#30] opened 2018-02-08 06:33 UTC
I have created a little JUnit test for BitcoinExtendedClient.getBlock. Calling this method with some blocks fails with the Exception:
```
[main] ERROR org.consensusj.jsonrpc.RPCClient - JsonProcessingException: {}
com.fasterxml.jackson.databind.exc.InvalidFormatException: Invalid Block
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@1ee29c84; line: 1, column: 11] (through reference chain: org.consensusj.jsonrpc.JsonRpcResponse["result"])
	at com.msgilligan.bitcoinj.json.conversion.BlockHexDeserializer.deserialize(BlockHexDeserializer.java:35)
	at com.msgilligan.bitcoinj.json.conversion.BlockHexDeserializer.deserialize(BlockHexDeserializer.java:1)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
...

```
My guess is that the block JSON format has changed since the last changes of Bitcoin Core and not adapted with ConsensusJ.

Here is the unit test:
```
package com.msgilligan.bitcoinj.rpc;

import java.net.URI;
import java.util.List;

import org.bitcoinj.core.Block;
import org.bitcoinj.core.NetworkParameters;
import org.bitcoinj.core.Sha256Hash;
import org.bitcoinj.core.Transaction;
import org.bitcoinj.params.MainNetParams;
import org.bitcoinj.params.TestNet3Params;
import org.junit.BeforeClass;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BitcoinExtendedClientTest2 {
	private static final Logger log = LoggerFactory.getLogger(BitcoinExtendedClientTest2.class);

	static BitcoinExtendedClient client;

	final static String host = "localhost";
	static String rpcuser = "test";
	static String rpcpassword = "test";

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		if (client == null) {
			NetworkParameters netParams = TestNet3Params.get();
			// NetworkParameters netParams = MainNetParams.get();
			URI server = RPCURI.getDefaultTestNetURI();
			client = new BitcoinExtendedClient(netParams, server, rpcuser, rpcpassword);
			RPCConfig config = new RPCConfig(TestNet3Params.get(), server, rpcuser, rpcpassword);
			client = new BitcoinExtendedClient(config);
			log.info(client.getBlockChainInfo().toString());
		}
	}

	@Test
	public void testGetBlock() throws Exception {
		// get last N blocks
		// log the block and their transactions
		int currentBlockDepth = client.getBlockCount();
		int N = 100;
		int successfulBlockRetrieves = 0;
		for (int i = currentBlockDepth; i > currentBlockDepth - N; i--) {
			Block block;
			try {
				block = client.getBlock(i);
				successfulBlockRetrieves++;
			} catch (Exception e) {
				Sha256Hash hash = client.getBlockHash(i);
				log.error("error getting block: " + i + " with hash: " + hash.toString());
				continue;
			}
			log.info("block: " + i + ": " + block.toString());
			List<Transaction> txs = block.getTransactions();
			for (Transaction t : txs) {
				log.info("transaction: " + t.toString());
			}
		}
		log.info("successfulBlockRetrieve: " + successfulBlockRetrieves + " of " + N);
	}
}

```

The last log writes the number of successful block retrievals. When I ran it, I got:
`[main] INFO com.msgilligan.bitcoinj.rpc.BitcoinExtendedClientTest2 - successfulBlockRetrieve: 24 of 100`

When I try to get the same block that failed in this unit test directly from the bitcoin-core cli it works. Here's one from the testnet for verification:
`[main] ERROR com.msgilligan.bitcoinj.rpc.BitcoinExtendedClientTest2 - error getting block: 1279694 with hash: 00000000000056dfdf0138c191040055c41fc7c07047ce6abb238227a2f3da6f`

Or am I call stuff wrong?

**Comment by msgilligan** [comment] 2018-03-17 23:21
I think this is a problem with **bitcoinj** not handling SegWit.

Have a look at this workaround in the **OmniJ** project:
https://github.com/OmniLayer/OmniJ/commit/8946dc38ef58438f0fda17b21b57deeb2908e9c0

(Sorry I didn't notice this an respond sooner.)

**Comment by msgilligan** [comment] 2018-03-17 23:31
**bitcoinj** is failing in `MessageSerializer::makeBlock` -- if you're up for it you could try building the latest **bitcoinj** from source and seeing if the in-progress SegWit support fixes the issue.

**Comment by msgilligan** [comment] 2018-03-17 23:37
OK, I also see that you've found the related **bitcoinj** issue:
https://github.com/bitcoinj/bitcoinj/issues/1348

**Comment by msgilligan** [comment] 2019-01-07 17:32
This is a duplicate of #23

**Closed by msgilligan** 2019-01-07 17:32 UTC
