### ISSUE TITLE
Numeric value (2345908848) out of range of int

### ISSUE THREAD

**Issue by zsh0103** [ConsensusJ/consensusj#44] opened 2018-07-30 12:44 UTC
com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2345908848) out of range of int
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@60940cc1; line: 1, column: 1562]
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@60940cc1; line: 1, column: 1552] (through reference chain: com.msgilligan.jsonrpc.JsonRpcResponse["result"]->com.msgilligan.bitcoinj.json.pojo.BlockInfo["nonce"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1611)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:513)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2938)
	at com.msgilligan.jsonrpc.RPCClient.send(RPCClient.java:119)
	at com.msgilligan.jsonrpc.AbstractRPCClient.sendForResult(AbstractRPCClient.java:55)
	at com.msgilligan.jsonrpc.AbstractRPCClient.send(AbstractRPCClient.java:89)
	at com.msgilligan.jsonrpc.AbstractRPCClient.send(AbstractRPCClient.java:96)
	at com.msgilligan.bitcoinj.rpc.BitcoinClient.getBlockInfo(BitcoinClient.java:278)

**Comment by msgilligan** [comment] 2018-07-30 16:21
What chain are you running on? It looks like it is the `nonce` field that is out of range and it looks like this is caused by it not having a leading zero. Can you please provide some information besides the stack trace?

**Comment by zsh0103** [comment] 2018-07-31 02:09
Hello, in bitcoins provids the environment, use the "OmniCliClient. GetBlockInfo (Sha256Hash txid)" query blockInfo, parameter class "com. Msgilligan. Bitcoinj. Json. Pojo. BlockInfo" the nonce is defined as an int type, lead to failure

**Comment by zsh0103** [comment] 2018-07-31 02:14
Query when height 324140 pieces of this BUG

**Comment by msgilligan** [comment] 2018-07-31 16:01
Fixed in 56f8137ce1d5cc6a7108774cde8a74df38c85768

**Closed by msgilligan** 2018-07-31 16:01 UTC

**Comment by msgilligan** [comment] 2018-07-31 17:44
The fix has been released as part of **ConsensusJ** `v0.3.0`.
