### ISSUE TITLE
getRawTransaction hexEncoded Parse error

### ISSUE THREAD

**Issue by qq592304796** [ConsensusJ/consensusj#46] opened 2018-10-12 08:28 UTC
bitcoin core 0.17.0

consensusj v0.3.0 

hexEncoded Parse error

testnet
txid:40d8fb846bf7d64537d63a3400dbeb5e848bd19449bf752f1582e28677f68092

![fail](https://user-images.githubusercontent.com/26601421/46857425-79673780-ce3b-11e8-8b03-beb949961e48.png)

The parsed transaction is not what I want

Is it because of the version of bitcoin core?

**Comment by msgilligan** [comment] 2018-11-02 02:10
I think this is a duplicate of #23 and #30 and can use the same workaround. Ultimately we need an updated bitcoinj.

> Is it because of the version of bitcoin core?

The new Bitcoin Core supports SegWit and bitcoinj doesn't (yet) -- so I think you'll have to use the workaround described in the other issues.

Let me know if this helps.

**Comment by msgilligan** [comment] 2019-01-07 17:33
This is a duplicate of #23.

**Closed by msgilligan** 2019-01-07 17:33 UTC
